site_name: Klodd
site_url: https://tjcsec.github.io/klodd/
repo_url: https://github.com/TJCSec/klodd/
edit_uri: blob/master/docs/content/
site_description: CTF challenge per-team instance runner
site_author: TJCSC
docs_dir: content
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: True
- footnotes
theme:
  name: material
  language: en
  features:
  - content.code.annotate
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: fontawesome/solid/sun
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: fontawesome/solid/moon
      name: Switch to light mode

nav:
- "Home": index.md
- "How To Use Klodd": how-to.md
- "Installation Guide":
  - "Prerequisites": install-guide/prerequisites.md
  - "Installation": install-guide/installation.md
  - "Configuration": install-guide/configuration.md
  - "Challenges": install-guide/challenges.md
- "Examples":
  - "Basic Deployment": examples/basic.md
  - "Challenges": examples/challenges.md
  - "Terraform": examples/terraform.md
